#!/usr/bin/env python
if len(sys.argv) != 3:
    print "usage: addtarget <database> <collection> <regex>"
    sys.exit(1)
    
_client = pymongo.MongoClient()
db = _client[sys.argv[1]][sys.argv[2]]

outf = open("targets","a")
print >>outf, "#addtargets %s:",sys.argv[3]
for r in db.find({"Path":{"$regex":sys.argv[3]}}):
    print >>outf, "# %s : %s" % (r["Metadata"]["SourceName"], r["Path"])
    print >>outf, r["uuid"]
printf >>outf, "\n"

outf.close()